-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQxwuFUrk3X42Asdf
Vpm5uRb+3ZS7sbMjleH5fIKVF1egCgYIKoZIzj0DAQehRANCAASJCoBSgqX+m92S
SHiZQgOQmxCewmibH5IgyzjKLxZ3t9QfhUm6tdaRk5Xx7eDarxbYI7QHVKMi2QFZ
qFnH8W/S
-----END PRIVATE KEY-----