name: derasy
description: Derasy Parents Portal - School Management & Student Tracking
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.1.0
  form_field_validator: ^1.1.0
  get_storage: ^2.1.1
  http: ^1.5.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/maskable-icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/png/white_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/animations/
    - assets/translations/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo-ExtraBold.ttf
          weight: 800
    - family: manrope
      fonts:
        - asset: assets/fonts/manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope-ExtraBold.ttf
          weight: 800